language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "4.2.0"
  - "iojs-v1"
  - "iojs-v2"
after_success: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
sudo: false
branches:
  only:
    - master